---
ID: "7ec8a9fe-2f3e-476b-be10-febbcaf7f991"
Parent: "ad44bef9-642b-44d9-8e60-5a4f0afca40b"
Template: "0437fee2-44c9-46a6-abe9-28858d9fee8c"
Path: "/sitecore/templates/Project/industry-verticals/Components/Products/Product Details"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250924T085324Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\sanduni.galagoda@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\sanduni.galagoda@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ede99a3a-009c-4064-9b5a-bb1701d2be70"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sanduni.galagoda@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250924T085324Z
