---
ID: "b86a1b6c-c131-42ce-afcf-d7fef4a543f5"
Parent: "4e869961-efef-4b47-bb69-170a251d689b"
Template: "98e60957-0783-4a9a-85cc-77dad30e9711"
Path: "/sitecore/content/industry-verticals/forma-lux/Home/Products"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{4D2B49E6-1130-444A-B22C-5C7E25D01B56}"
- ID: "1fbc6a49-6281-48ee-87e9-a3970b145adb"
  Hint: NavigationFilter
  Value: "{D063E9D1-C7B5-4B1E-B31E-69886C9C59F5}"
- ID: "25f9b35b-0c2c-4f43-ae2f-1d30eb1f2b6b"
  Hint: ogImage
  Value: |
    <Image src="https://starter-verticals.sitecoresandbox.cloud/api/public/content/76645-LandingPageHero-2000x600?v=73ec6612" dam-id="-7WQV-NRRkCpMe8JV60RlQ" width="2000" height="600" alt="products-meta.png" dam-content-type="Image" thumbnailsrc="https://starter-verticals.sitecoresandbox.cloud/api/gateway/76645/thumbnail" />
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{072CD27A-6AC9-457E-9649-37051EFC336C}" />
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "f56c1067-733b-40df-a78e-c3427c43239e"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{3447123F-7CA9-4350-9085-20C4F632B7EE}"
          s:id="{613A3675-953D-4AD1-877A-48D24A28977D}"
          s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
          s:ph="headless-main" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "13fe722e-a8c7-4432-a983-23fb28ffab05"
      Hint: metadataKeywords
      Value: "Forma Lux, luxury furniture, sustainable furniture, modern furniture collections, handcrafted sofas, minimalist chairs, oak tables, timeless design, eco-friendly furniture, modular seating"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250922T091044Z
    - ID: "32c603c2-c858-4138-8fcb-8e18a5ad8240"
      Hint: metadataTitle
      Value: Products | Browse all of our products
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Products
    - ID: "4ff91248-33ab-4254-b6f7-2618fd0aebae"
      Hint: Title
      Value: Products
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "6b43d550-6d5f-46ce-ac84-3d9493c45bc6"
      Hint: metadataDescription
      Value: Explore Forma Lux’s full range of sustainable furniture collections — timeless sofas, chairs, and tables crafted with precision, natural materials, and enduring elegance. Designed to bring warmth, balance, and sophistication to every space.
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2ecb72ae-6619-4284-beaf-43d6a268b9d5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "d3886445-9ee0-46a0-ae5e-8857dd6b395f"
      Hint: pageSummary
      Value: Forma Lux offers a curated selection of sustainable luxury furniture designed to elevate modern living. Each collection — from modular sofas to sculptural tables — reflects a commitment to craftsmanship, quality, and intentional design. Every piece is made to endure, bringing refined simplicity and lasting beauty to the spaces people call home.
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251223T145809Z
- Language: "es-ES"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250925T123933Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\movin.tilakaratne@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\movin.tilakaratne@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fa9adf99-e33b-484a-b979-1661d7eae9db"
    - ID: "9857f526-390f-48df-b6d1-1a97cc328e8f"
      Hint: __Version Name
      Value: 
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\movin.tilakaratne@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250925T123933Z
  - Version: 2
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "13fe722e-a8c7-4432-a983-23fb28ffab05"
      Hint: metadataKeywords
      Value: Forma Lux, muebles de lujo, muebles sostenibles, colecciones de muebles modernos, sofás hechos a mano, sillas minimalistas, mesas de roble, diseño atemporal, muebles ecológicos, asientos modulares
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250922T091044Z
    - ID: "32c603c2-c858-4138-8fcb-8e18a5ad8240"
      Hint: metadataTitle
      Value: Productos | Explora todos nuestros productos
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Productos
    - ID: "4ff91248-33ab-4254-b6f7-2618fd0aebae"
      Hint: Title
      Value: Productos
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "6b43d550-6d5f-46ce-ac84-3d9493c45bc6"
      Hint: metadataDescription
      Value: "Explora la gama completa de colecciones de muebles sostenibles de Forma Lux: sofás, sillas y mesas atemporales elaborados con precisión, materiales naturales y elegancia duradera. Diseñados para aportar calidez, equilibrio y sofisticación a cada espacio."
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "428af7f5-0867-4ab0-80db-5ea025493382"
    - ID: "9857f526-390f-48df-b6d1-1a97cc328e8f"
      Hint: __Version Name
      Value: AI translated
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\movin.tilakaratne@sitecore.com
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 
    - ID: "d3886445-9ee0-46a0-ae5e-8857dd6b395f"
      Hint: pageSummary
      Value: Forma Lux ofrece una selección curada de muebles de lujo sostenibles diseñados para elevar la vida moderna. Cada colección, desde sofás modulares hasta mesas escultóricas, refleja un compromiso con la artesanía, la calidad y el diseño intencional. Cada pieza está hecha para perdurar, aportando simplicidad refinada y belleza duradera a los espacios que las personas llaman hogar.
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251219T104259Z
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "13fe722e-a8c7-4432-a983-23fb28ffab05"
      Hint: metadataKeywords
      Value: Forma Lux, meubles de luxe, meubles durables, collections de meubles modernes, canapés faits à la main, chaises minimalistes, tables en chêne, design intemporel, meubles écologiques, sièges modulaires
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250922T091044Z
    - ID: "32c603c2-c858-4138-8fcb-8e18a5ad8240"
      Hint: metadataTitle
      Value: Produits | Parcourez tous nos produits
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Produits
    - ID: "4ff91248-33ab-4254-b6f7-2618fd0aebae"
      Hint: Title
      Value: Produits
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "6b43d550-6d5f-46ce-ac84-3d9493c45bc6"
      Hint: metadataDescription
      Value: Explorez la gamme complète de collections de meubles durables de Forma Lux — des canapés, chaises et tables intemporels fabriqués avec précision, matériaux naturels et élégance durable. Conçus pour apporter chaleur, équilibre et sophistication à chaque espace.
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fb50e7d3-dd06-4000-afe4-2e63cb002834"
    - ID: "9857f526-390f-48df-b6d1-1a97cc328e8f"
      Hint: __Version Name
      Value: AI translated
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\isuru.bandara@sitecore.com
    - ID: "d3886445-9ee0-46a0-ae5e-8857dd6b395f"
      Hint: pageSummary
      Value: Forma Lux offre une sélection soignée de meubles de luxe durables conçus pour élever le mode de vie moderne. Chaque collection — des canapés modulaires aux tables sculpturales — reflète un engagement envers l'artisanat, la qualité et le design intentionnel. Chaque pièce est faite pour durer, apportant une simplicité raffinée et une beauté durable aux espaces que les gens appellent chez eux.
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251217T110105Z
- Language: "fr-FR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250925T123832Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\movin.tilakaratne@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\movin.tilakaratne@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "16687898-31d0-499b-8f79-5e906646518f"
    - ID: "9857f526-390f-48df-b6d1-1a97cc328e8f"
      Hint: __Version Name
      Value: 
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\movin.tilakaratne@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250925T123832Z
